on:
  push:
    branches: master
  pull_request:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache _freeze
        uses: actions/cache@v4
        with:
          path: _freeze
          key: ${{ runner.os }}-quarto-freeze-${{ hashFiles('**/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-quarto-freeze-

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libv8-dev libboost-all-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
        
      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2
            any::ggplot2
            any::dplyr
            any::tidyr
            any::tibble
            any::purrr
            any::tidyverse
            any::broom
            any::scales
            any::patchwork
            any::ggiraph
            any::ggpubr
            any::stochtree
            any::CausalImpact
            any::bsynth
            any::rstan
            any::bayesplot
            any::posterior
            any::vizdraws
            any::glossary
            any::furrr
            any::tictoc
            any::glue
            any::shinydashboard
            any::shinylive
            any::remotes
            any::MatchIt
            any::coda
            any::rpart
            any::rpart.plot
            any::shiny
            any::shinybusy
            any::arm
            any::future
            any::lubridate
            google/imt
            google/biva
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
